// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: chat.proto

package chat

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type Chunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre    string `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Parte     string `protobuf:"bytes,2,opt,name=parte,proto3" json:"parte,omitempty"`
	NumPartes uint64 `protobuf:"varint,3,opt,name=numPartes,proto3" json:"numPartes,omitempty"`
	Buffer    []byte `protobuf:"bytes,4,opt,name=buffer,proto3" json:"buffer,omitempty"`
	Port      string `protobuf:"bytes,5,opt,name=Port,proto3" json:"Port,omitempty"`
	Algo      string `protobuf:"bytes,6,opt,name=Algo,proto3" json:"Algo,omitempty"`
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *Chunk) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Chunk) GetParte() string {
	if x != nil {
		return x.Parte
	}
	return ""
}

func (x *Chunk) GetNumPartes() uint64 {
	if x != nil {
		return x.NumPartes
	}
	return 0
}

func (x *Chunk) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

func (x *Chunk) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Chunk) GetAlgo() string {
	if x != nil {
		return x.Algo
	}
	return ""
}

type PropuestaRespuesta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nombre string `protobuf:"bytes,1,opt,name=Nombre,proto3" json:"Nombre,omitempty"`
	Total  string `protobuf:"bytes,2,opt,name=Total,proto3" json:"Total,omitempty"`
	Nd1    string `protobuf:"bytes,3,opt,name=nd1,proto3" json:"nd1,omitempty"`
	Nd2    string `protobuf:"bytes,4,opt,name=nd2,proto3" json:"nd2,omitempty"`
	Nd3    string `protobuf:"bytes,5,opt,name=nd3,proto3" json:"nd3,omitempty"`
	Intn1  string `protobuf:"bytes,6,opt,name=intn1,proto3" json:"intn1,omitempty"`
	Intn2  string `protobuf:"bytes,7,opt,name=intn2,proto3" json:"intn2,omitempty"`
	Intn3  string `protobuf:"bytes,8,opt,name=intn3,proto3" json:"intn3,omitempty"`
}

func (x *PropuestaRespuesta) Reset() {
	*x = PropuestaRespuesta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PropuestaRespuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropuestaRespuesta) ProtoMessage() {}

func (x *PropuestaRespuesta) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropuestaRespuesta.ProtoReflect.Descriptor instead.
func (*PropuestaRespuesta) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *PropuestaRespuesta) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *PropuestaRespuesta) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *PropuestaRespuesta) GetNd1() string {
	if x != nil {
		return x.Nd1
	}
	return ""
}

func (x *PropuestaRespuesta) GetNd2() string {
	if x != nil {
		return x.Nd2
	}
	return ""
}

func (x *PropuestaRespuesta) GetNd3() string {
	if x != nil {
		return x.Nd3
	}
	return ""
}

func (x *PropuestaRespuesta) GetIntn1() string {
	if x != nil {
		return x.Intn1
	}
	return ""
}

func (x *PropuestaRespuesta) GetIntn2() string {
	if x != nil {
		return x.Intn2
	}
	return ""
}

func (x *PropuestaRespuesta) GetIntn3() string {
	if x != nil {
		return x.Intn3
	}
	return ""
}

type Biblioteca struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Largo  string `protobuf:"bytes,1,opt,name=largo,proto3" json:"largo,omitempty"`
	Libros string `protobuf:"bytes,2,opt,name=libros,proto3" json:"libros,omitempty"`
}

func (x *Biblioteca) Reset() {
	*x = Biblioteca{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Biblioteca) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Biblioteca) ProtoMessage() {}

func (x *Biblioteca) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Biblioteca.ProtoReflect.Descriptor instead.
func (*Biblioteca) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{3}
}

func (x *Biblioteca) GetLargo() string {
	if x != nil {
		return x.Largo
	}
	return ""
}

func (x *Biblioteca) GetLibros() string {
	if x != nil {
		return x.Libros
	}
	return ""
}

type Propuesta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nd1   string `protobuf:"bytes,3,opt,name=nd1,proto3" json:"nd1,omitempty"`
	Nd2   string `protobuf:"bytes,4,opt,name=nd2,proto3" json:"nd2,omitempty"`
	Nd3   string `protobuf:"bytes,5,opt,name=nd3,proto3" json:"nd3,omitempty"`
	Intn1 string `protobuf:"bytes,6,opt,name=intn1,proto3" json:"intn1,omitempty"`
	Intn2 string `protobuf:"bytes,7,opt,name=intn2,proto3" json:"intn2,omitempty"`
	Intn3 string `protobuf:"bytes,8,opt,name=intn3,proto3" json:"intn3,omitempty"`
}

func (x *Propuesta) Reset() {
	*x = Propuesta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Propuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Propuesta) ProtoMessage() {}

func (x *Propuesta) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Propuesta.ProtoReflect.Descriptor instead.
func (*Propuesta) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{4}
}

func (x *Propuesta) GetNd1() string {
	if x != nil {
		return x.Nd1
	}
	return ""
}

func (x *Propuesta) GetNd2() string {
	if x != nil {
		return x.Nd2
	}
	return ""
}

func (x *Propuesta) GetNd3() string {
	if x != nil {
		return x.Nd3
	}
	return ""
}

func (x *Propuesta) GetIntn1() string {
	if x != nil {
		return x.Intn1
	}
	return ""
}

func (x *Propuesta) GetIntn2() string {
	if x != nil {
		return x.Intn2
	}
	return ""
}

func (x *Propuesta) GetIntn3() string {
	if x != nil {
		return x.Intn3
	}
	return ""
}

var File_chat_proto protoreflect.FileDescriptor

var file_chat_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x68,
	0x61, 0x74, 0x22, 0x1d, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x22, 0x93, 0x01, 0x0a, 0x05, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d,
	0x62, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x72, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x75, 0x6d,
	0x50, 0x61, 0x72, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6e, 0x75,
	0x6d, 0x50, 0x61, 0x72, 0x74, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x50,
	0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x6c, 0x67, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x41, 0x6c, 0x67, 0x6f, 0x22, 0xba, 0x01, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x70,
	0x75, 0x65, 0x73, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x16,
	0x0a, 0x06, 0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x4e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x10, 0x0a, 0x03,
	0x6e, 0x64, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x64, 0x31, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x64, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x64, 0x32,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x64, 0x33, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e,
	0x64, 0x33, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x6e, 0x31, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x6e, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x6e,
	0x32, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x6e, 0x32, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x74, 0x6e, 0x33, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x6e, 0x74, 0x6e, 0x33, 0x22, 0x3a, 0x0a, 0x0a, 0x42, 0x69, 0x62, 0x6c, 0x69, 0x6f, 0x74, 0x65,
	0x63, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x72, 0x67, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x61, 0x72, 0x67, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x69, 0x62, 0x72,
	0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x69, 0x62, 0x72, 0x6f, 0x73,
	0x22, 0x83, 0x01, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x64, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x64, 0x31,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x64, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e,
	0x64, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x64, 0x33, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6e, 0x64, 0x33, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x6e, 0x31, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x6e, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x74, 0x6e, 0x32, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x6e, 0x32,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x6e, 0x33, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x69, 0x6e, 0x74, 0x6e, 0x33, 0x32, 0x80, 0x03, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x11, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x41, 0x4e, 0x6f, 0x64, 0x6f, 0x12, 0x0b, 0x2e, 0x63, 0x68,
	0x61, 0x74, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x1a, 0x0d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x10, 0x41, 0x63, 0x65,
	0x70, 0x74, 0x61, 0x72, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x12, 0x18, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x1a, 0x18, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x50,
	0x72, 0x6f, 0x70, 0x75, 0x65, 0x73, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x75, 0x65, 0x73, 0x74,
	0x61, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x16, 0x45, 0x6e, 0x76, 0x69, 0x61, 0x72, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x65, 0x4e, 0x6f, 0x64, 0x6f, 0x73, 0x12, 0x0b, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x1a, 0x0d, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0f, 0x50,
	0x65, 0x64, 0x69, 0x72, 0x42, 0x69, 0x62, 0x6c, 0x69, 0x6f, 0x74, 0x65, 0x63, 0x61, 0x12, 0x0d,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x10, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x2e, 0x42, 0x69, 0x62, 0x6c, 0x69, 0x6f, 0x74, 0x65, 0x63, 0x61, 0x22,
	0x00, 0x12, 0x2e, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x12, 0x0d,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x10, 0x2e,
	0x63, 0x68, 0x61, 0x74, 0x2e, 0x42, 0x69, 0x62, 0x6c, 0x69, 0x6f, 0x74, 0x65, 0x63, 0x61, 0x22,
	0x00, 0x12, 0x2c, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x65, 0x72, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12,
	0x0d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0d,
	0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12,
	0x28, 0x0a, 0x06, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x0d, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData = file_chat_proto_rawDesc
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(file_chat_proto_rawDescData)
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_chat_proto_goTypes = []interface{}{
	(*Message)(nil),            // 0: chat.Message
	(*Chunk)(nil),              // 1: chat.Chunk
	(*PropuestaRespuesta)(nil), // 2: chat.PropuestaRespuesta
	(*Biblioteca)(nil),         // 3: chat.Biblioteca
	(*Propuesta)(nil),          // 4: chat.Propuesta
}
var file_chat_proto_depIdxs = []int32{
	1, // 0: chat.ChatService.ChunkClienteANodo:input_type -> chat.Chunk
	2, // 1: chat.ChatService.AceptarPropuesta:input_type -> chat.PropuestaRespuesta
	1, // 2: chat.ChatService.EnviarChunksEntreNodos:input_type -> chat.Chunk
	0, // 3: chat.ChatService.PedirBiblioteca:input_type -> chat.Message
	0, // 4: chat.ChatService.LogChunks:input_type -> chat.Message
	0, // 5: chat.ChatService.TraerChunk:input_type -> chat.Message
	0, // 6: chat.ChatService.Estado:input_type -> chat.Message
	0, // 7: chat.ChatService.ChunkClienteANodo:output_type -> chat.Message
	2, // 8: chat.ChatService.AceptarPropuesta:output_type -> chat.PropuestaRespuesta
	0, // 9: chat.ChatService.EnviarChunksEntreNodos:output_type -> chat.Message
	3, // 10: chat.ChatService.PedirBiblioteca:output_type -> chat.Biblioteca
	3, // 11: chat.ChatService.LogChunks:output_type -> chat.Biblioteca
	0, // 12: chat.ChatService.TraerChunk:output_type -> chat.Message
	0, // 13: chat.ChatService.Estado:output_type -> chat.Message
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PropuestaRespuesta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Biblioteca); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Propuesta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_rawDesc = nil
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatServiceClient interface {
	ChunkClienteANodo(ctx context.Context, in *Chunk, opts ...grpc.CallOption) (*Message, error)
	AceptarPropuesta(ctx context.Context, in *PropuestaRespuesta, opts ...grpc.CallOption) (*PropuestaRespuesta, error)
	EnviarChunksEntreNodos(ctx context.Context, in *Chunk, opts ...grpc.CallOption) (*Message, error)
	PedirBiblioteca(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Biblioteca, error)
	LogChunks(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Biblioteca, error)
	TraerChunk(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	Estado(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) ChunkClienteANodo(ctx context.Context, in *Chunk, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/chat.ChatService/ChunkClienteANodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) AceptarPropuesta(ctx context.Context, in *PropuestaRespuesta, opts ...grpc.CallOption) (*PropuestaRespuesta, error) {
	out := new(PropuestaRespuesta)
	err := c.cc.Invoke(ctx, "/chat.ChatService/AceptarPropuesta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) EnviarChunksEntreNodos(ctx context.Context, in *Chunk, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/chat.ChatService/EnviarChunksEntreNodos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) PedirBiblioteca(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Biblioteca, error) {
	out := new(Biblioteca)
	err := c.cc.Invoke(ctx, "/chat.ChatService/PedirBiblioteca", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) LogChunks(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Biblioteca, error) {
	out := new(Biblioteca)
	err := c.cc.Invoke(ctx, "/chat.ChatService/LogChunks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) TraerChunk(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/chat.ChatService/TraerChunk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) Estado(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/chat.ChatService/Estado", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
type ChatServiceServer interface {
	ChunkClienteANodo(context.Context, *Chunk) (*Message, error)
	AceptarPropuesta(context.Context, *PropuestaRespuesta) (*PropuestaRespuesta, error)
	EnviarChunksEntreNodos(context.Context, *Chunk) (*Message, error)
	PedirBiblioteca(context.Context, *Message) (*Biblioteca, error)
	LogChunks(context.Context, *Message) (*Biblioteca, error)
	TraerChunk(context.Context, *Message) (*Message, error)
	Estado(context.Context, *Message) (*Message, error)
}

// UnimplementedChatServiceServer can be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (*UnimplementedChatServiceServer) ChunkClienteANodo(context.Context, *Chunk) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChunkClienteANodo not implemented")
}
func (*UnimplementedChatServiceServer) AceptarPropuesta(context.Context, *PropuestaRespuesta) (*PropuestaRespuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AceptarPropuesta not implemented")
}
func (*UnimplementedChatServiceServer) EnviarChunksEntreNodos(context.Context, *Chunk) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarChunksEntreNodos not implemented")
}
func (*UnimplementedChatServiceServer) PedirBiblioteca(context.Context, *Message) (*Biblioteca, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PedirBiblioteca not implemented")
}
func (*UnimplementedChatServiceServer) LogChunks(context.Context, *Message) (*Biblioteca, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogChunks not implemented")
}
func (*UnimplementedChatServiceServer) TraerChunk(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TraerChunk not implemented")
}
func (*UnimplementedChatServiceServer) Estado(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Estado not implemented")
}

func RegisterChatServiceServer(s *grpc.Server, srv ChatServiceServer) {
	s.RegisterService(&_ChatService_serviceDesc, srv)
}

func _ChatService_ChunkClienteANodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Chunk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ChunkClienteANodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/ChunkClienteANodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ChunkClienteANodo(ctx, req.(*Chunk))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_AceptarPropuesta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PropuestaRespuesta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).AceptarPropuesta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/AceptarPropuesta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).AceptarPropuesta(ctx, req.(*PropuestaRespuesta))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_EnviarChunksEntreNodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Chunk)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).EnviarChunksEntreNodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/EnviarChunksEntreNodos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).EnviarChunksEntreNodos(ctx, req.(*Chunk))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_PedirBiblioteca_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).PedirBiblioteca(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/PedirBiblioteca",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).PedirBiblioteca(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_LogChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).LogChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/LogChunks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).LogChunks(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_TraerChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).TraerChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/TraerChunk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).TraerChunk(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_Estado_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).Estado(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.ChatService/Estado",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).Estado(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChunkClienteANodo",
			Handler:    _ChatService_ChunkClienteANodo_Handler,
		},
		{
			MethodName: "AceptarPropuesta",
			Handler:    _ChatService_AceptarPropuesta_Handler,
		},
		{
			MethodName: "EnviarChunksEntreNodos",
			Handler:    _ChatService_EnviarChunksEntreNodos_Handler,
		},
		{
			MethodName: "PedirBiblioteca",
			Handler:    _ChatService_PedirBiblioteca_Handler,
		},
		{
			MethodName: "LogChunks",
			Handler:    _ChatService_LogChunks_Handler,
		},
		{
			MethodName: "TraerChunk",
			Handler:    _ChatService_TraerChunk_Handler,
		},
		{
			MethodName: "Estado",
			Handler:    _ChatService_Estado_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat.proto",
}
